### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by MattKetmo** [openl10n/openl10n#14]
_Some notes/ideas to implement for in openl10n core app. 
This is just a simple task list. Issues with more description will be created on the fly._
# User

_Note: everything must be under the UserBundle_
## Profile
- [x] Profile general: edit (fullname + email + prefered locale) `/settings/`
- [x] Profile password: edit password `/settings/password`
- [x] Profile delete account `/settings/leave`
- [x] Public profile at `/profile/{username}`
## Sign-Up
- [ ] Create basic registration page (`/signup`) - username + email + fullname? + password
- [ ] Add OAuth login (github + twitter) — see #4
- [ ] Add LDAP login
## Misc
- [x] Add Gravatar image
- [x] Add identicon image
# Translations
## File
- [x] Manage options when importing translation file
- [x] Manage options when exporting translation file
- [ ] Allow specifying format if extension is not recognized
- [ ] Add format (Android/iOS ?)
- [ ] Keep resources name (to known imported format + path?) — see #20 
- [ ] Automatic import by fetching a given URL (eg. http://example.org/foobar.yml)
## Meta
- [ ] Add history
- [ ] Add description/context data for each translation (separate table one-to-one)
- [ ] Add tags f.e. translation (separate table one-to-many) - auto tag when import?
- [ ] Add screenshots (separate table many-to-many)
- [ ] Add comment system
- [ ] Add suggestion system (crowdsourcing)
- [ ] Add attributes : excluded + skip review
- [ ] Handle pluralization
# Release process

_CoreBundle_

A release is a "snapshot" of the translations in a project
It contains:
- a slug (current timestamp by default or version number)
- a datetime
- description

When creating a new release, a webhook should be invoked.

To be defined: do we need to version translation (eg. create an archive to snapshot)
- [ ] Add release system (create action + delete? - no edit)
- [ ] Add webhook mecanism (need asynchronous job)
- [ ] Add connection with GitHub (in order to make automatic PR)
# UI
- [ ] Use of selectize.js or chosen.js to select locales
- [ ] Upload file with drag and drop
- [x] Improve UI by creating styleguide (eg. flat card panel)
- [x] Update editor UI (remove main navbar)
- [x] Update login page (remove main navbar)
- [ ] Easy project creation funnel (step to step process from project creation to file import)

To Be Defined: information to display on project list + project page

Need to be customizable/card system (hinclude.js?)
# Project
- [ ] Avatar
- [ ] Type (website/android/ios/etc...)
- [ ] Add attributes : description, project URL, CONTRIBUTING.md-like URL
- [ ] URL code source (usefull for github link)
# Roles

Add roles management.
Example:
- manager (admin power) - by project & global
- reviewer (can review + edit translation)
- editor (can edit but not review)
- read only
- no access to project (project can be public ?)
- coordinator/collaborator? (ie. responsible of one or many languages)
# Editor

_EditorBundle_
- [ ] Search with text (mysql? + elasticsearch)
- [ ] Select by reviewed/untranslated phrases
- [ ] Adjust scroll on translation selection
- [ ] Improve shortkey (eg. save + go next)
- [ ] Allow select all domains (and search translation of all project)
- [ ] Add pagination (Infinite Scroll)
- [ ] Enable other filters
- [ ] Detect plurialization
- [ ] Limit phrase length
- [ ] Bulk editing (tag, screenshot, review)
- [ ] Add machine-translator (ie. Google Translate / Bing)
# Stats

_StatsBundle_

For each project + each locale (in a project):
- [ ] Get count of translated/reviewed translations
- [ ] Get count of phrases/words
# Feed
- [ ] Log each activity (translated phrase, new comment, file import, etc.)
- [ ] Create dashboard to list activity
- [ ] Keep track where users have been involved
- [ ] Display user activiy
- [ ] Display project activiy
# Notifications
- [ ] Summary of stat to collaborators (email)
# Glossary

(To be defined)
# Tasks

(To be defined)

example : "Translate xx_XX before Y-m-d"
# Auth
- [ ] Add API key system
- [ ] Add OAuth token system
# Docs

Learn section - _DocBundle_ or separate site (support.openl10n.io)
